-- HOURLY RATE AND TOTAL HOURS SPENT BY CONSULTANTS BY CONTACTID, CONSULTANT AND STATUS
SELECT [STATUS], AVG(OFC.HOURLY_RATE) AS OPP_HOURLY_RATE, COUNT(*) AS TOTAL_HOURS, SUM(OFC.TRAVEL_DAYS) AS TOTAL_TRAVEL_DAYS,
OFC.CONSULTANT, OC.CONTACTID FROM sysdba.OPPORTUNITY O
LEFT JOIN sysdba.OPPORTUNITY_CONTACT OC
ON O.OPPORTUNITYID = OC.OPPORTUNITYID
LEFT JOIN sysdba.OPPTY_FSI_CONSULTING OFC
ON O.OPPORTUNITYID = OFC.OPPORTUNITYID
WHERE OFC.HOURLY_RATE IS NOT NULL AND OFC.TRAVEL_DAYS IS NOT NULL
GROUP BY CONSULTANT, CONTACTID, [STATUS]
ORDER BY [STATUS], CONSULTANT, AVG(OFC.HOURLY_RATE)