
WITH CTE (ACCOUNTID, SALESPERSON, NO_CALLS_PER_ACCOUNT, SIGNED_YEAR) AS
(SELECT HIS.ACCOUNTID, AFC.SALESPERSON, COUNT(*), YEAR(SIGNED_DATE) AS SIGNED_YEAR FROM SYSDBA.HISTORY HIS INNER JOIN SYSDBA.ACCOUNT_FSI_CONTRACT AFC
ON HIS.ACCOUNTID = AFC.ACCOUNTID
WHERE CATEGORY = 'CALL'
GROUP BY SALESPERSON, HIS.ACCOUNTID, SIGNED_DATE HAVING COUNT(HIS.ACCOUNTID) in (2,3) AND SALESPERSON IS NOT NULL)
SELECT SALESPERSON, COUNT(*) AS NO_OF_TIMES, SIGNED_YEAR FROM CTE GROUP BY SALESPERSON, SIGNED_YEAR ORDER BY SALESPERSON, SIGNED_YEAR