-- FROM THE QUERY BELOW, WE GOT THE AVERAGE RESPONSE TIME FROM DIFFERENT CAMPAIGNS BASED ON CALLTOACTION
-- IN OUR OPINION WE THINK WE CAN TAKE A MEDIAN OF ALL THE AVERAGE TIMES AS A FAIR CUTOFF AND CHOOSE THE CAMPAIGN TYPE WITH GOOD NUMBER 
-- OF ACCOUNTS AS A SUCCESSFUL CAMPAIGN
SELECT CAMPAIGNNAME, CALLTOACTION, A.[TYPE], AVG(DATEDIFF(DAY, ACTUALLAUNCHDATE, RESPONSEDATE)) AS AVG_RESPONSE_TIME_DAYS, COUNT(*) AS NO_OF_ACCOUNTS
FROM sysdba.CAMPAIGN C JOIN sysdba.TARGETRESPONSE T ON C.CAMPAIGNID = T.CAMPAIGNID 
JOIN sysdba.CONTACT CO ON T.CONTACTID = CO.CONTACTID
JOIN sysdba.ACCOUNT A ON CO.ACCOUNTID = A.ACCOUNTID
GROUP BY CAMPAIGNNAME, CALLTOACTION, A.[TYPE]
HAVING AVG(DATEDIFF(DAY, ACTUALLAUNCHDATE, RESPONSEDATE)) > 0
ORDER BY CAMPAIGNNAME, CALLTOACTION, A.[TYPE]