--Sales by product
SELECT O.STATUS, AP.PRODUCTID, P.NAME AS PRODUCT_NAME, COUNT(*) AS SALES_BY_PRODUCT FROM SYSDBA.OPPORTUNITY O JOIN SYSDBA.ACCOUNTPRODUCT AP
ON O.ACCOUNTID = AP.ACCOUNTID LEFT JOIN dbo.PRODUCTS P ON P.PRODUCTID = AP.PRODUCTID
GROUP BY STATUS, AP.PRODUCTID, P.NAME
HAVING STATUS = 'Invoiced'
ORDER BY STATUS, COUNT(*) DESC, AP.PRODUCTID